# Generated by Django 3.2.9 on 2021-11-20 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ing_count', models.IntegerField()),
                ('unit_measurement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название рецепта')),
                ('teg', multiselectfield.db.fields.MultiSelectField(choices=[('Z', 'Завтрак'), ('O', 'Обед'), ('Y', 'Ужин')], max_length=5)),
                ('text', models.TextField(help_text='Введите текст описания', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Добавьте изображение', upload_to='recipes/', verbose_name='Загрузить фото')),
                ('time', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
