# Generated by Django 3.2.9 on 2021-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='app.Ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
