# Generated by Django 3.2.9 on 2021-11-21 20:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='app.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='teg',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин')], max_length=22),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
    ]
