# Generated by Django 3.2.9 on 2021-11-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_measurement',
            field=models.CharField(max_length=20, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ing_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingredient', verbose_name='Ингредиент'),
        ),
    ]
