# Generated by Django 3.2.9 on 2021-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211122_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', to='app.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
