# Generated by Django 3.2.9 on 2021-11-27 21:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211127_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['author__name', 'pub_date__month'], verbose_name='slug'),
        ),
    ]
