# Generated by Django 3.2.9 on 2021-12-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shoplist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoplist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
